apiVersion: qbec.io/v1alpha1
kind: App
metadata:
  name: hahaton
spec:
  namespaceTagSuffix: true

  environments:
    default:
      defaultNamespace: default
      server: https://127.0.0.1:36577
    prod:
      defaultNamespace: default
      server: https://192.168.32.131:6443

  vars:
    external:
      - name: helmTemplate
        default: /home/master/nginx

    computed:
      - name: replaceHelmValues
        code: |
          local defaultEnv = import 'environments/default.libsonnet';

          local base = defaultEnv.components.default;
          local tag = std.extVar('qbec.io/tag');
          local tagged = std.get(defaultEnv.components, tag, base);

          local merged = std.mergePatch(base, tagged);

          {
            command: 'helm',
            args: [
              'template',
              '--dry-run',
              '-f', '-',
              std.extVar('helmTemplate')
            ],
            env: {},
            stdin: std.toString(merged),
          }

  dataSources:
    - exec://helmApiResources?configVar=replaceHelmValues
